definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.APIError:
    properties:
      message:
        type: string
    type: object
  models.APIStatus:
    properties:
      client_status:
        type: string
    type: object
  models.File:
    properties:
      public_url:
        type: string
    type: object
  models.Image:
    properties:
      public_url:
        type: string
    type: object
  models.User:
    properties:
      aws_access_key_id:
        type: string
      aws_bucket:
        type: string
      aws_region:
        type: string
      aws_secret_access_key:
        type: string
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        type: string
      email_verified_at:
        type: string
      fcm_token:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      remember_token:
        type: string
      reset_password_token:
        type: string
      token:
        type: string
      updated_at:
        type: string
    type: object
  requests.CreateBase64FileInput:
    properties:
      base64:
        type: string
      extension:
        type: string
      file_path:
        type: string
    required:
    - base64
    - extension
    type: object
  requests.CreateBase64ImageInput:
    properties:
      base64:
        type: string
      extension:
        type: string
      file_path:
        type: string
      height:
        type: integer
      width:
        type: integer
    required:
    - base64
    - extension
    type: object
  requests.CreateChartRadar:
    properties:
      Indicators:
        items:
          properties:
            color:
              example: '#000000'
              type: string
            max:
              example: 100
              type: number
            min:
              example: 0
              type: number
            name:
              example: Level 1
              type: string
          required:
          - color
          - max
          - min
          - name
          type: object
        type: array
      MultiSeries:
        items:
          properties:
            data:
              items:
                properties:
                  name:
                    example: Level
                    type: string
                  value:
                    items:
                      type: number
                    type: array
                required:
                - name
                - value
                type: object
              type: array
            itemStyle:
              properties:
                color:
                  example: rgba(47, 85, 220, 0.2)
                  type: string
              required:
              - color
              type: object
            name:
              example: TARGET
              type: string
          required:
          - data
          - itemStyle
          - name
          type: object
        type: array
      backgroundColor:
        example: '#ffffff'
        type: string
      height:
        example: 500px
        type: string
      legend:
        properties:
          data:
            example:
            - TARGET
            - RESULT
            items:
              type: string
            type: array
          show:
            example: true
            type: boolean
        required:
        - data
        - show
        type: object
      splitLine:
        properties:
          lineStyle:
            properties:
              color:
                example: '#595757'
                type: string
              opacity:
                example: 0.5
                type: number
              type:
                example: solid
                type: string
            required:
            - color
            - opacity
            - type
            type: object
          show:
            example: true
            type: boolean
        required:
        - lineStyle
        - show
        type: object
      splitNumber:
        example: 5
        type: integer
      width:
        example: 900px
        type: string
    required:
    - Indicators
    - MultiSeries
    - backgroundColor
    - legend
    - splitLine
    - splitNumber
    type: object
  requests.CreateUserInput:
    properties:
      aws_access_key_id:
        type: string
      aws_bucket:
        type: string
      aws_region:
        type: string
      aws_secret_access_key:
        type: string
      email:
        type: string
      fcm_token:
        type: string
      name:
        type: string
      password:
        type: string
      remember_token:
        type: string
    required:
    - aws_access_key_id
    - aws_bucket
    - aws_region
    - aws_secret_access_key
    - email
    - name
    - password
    type: object
  requests.ForgotPasswordInput:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  requests.LoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  requests.RecoverPasswordInput:
    properties:
      password:
        type: string
      reset_password_token:
        type: string
    required:
    - password
    - reset_password_token
    type: object
  requests.UpdateUserFcmTokenInput:
    properties:
      fcm_token:
        type: string
    required:
    - fcm_token
    type: object
  requests.UpdateUserInput:
    properties:
      aws_access_key_id:
        type: string
      aws_bucket:
        type: string
      aws_region:
        type: string
      aws_secret_access_key:
        type: string
      email:
        type: string
      fcm_token:
        type: string
      name:
        type: string
      password:
        type: string
      remember_token:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: contact@spotec.app
    name: API Support
    url: https://spotec.app/contato/
paths:
  /charts/radar/create:
    post:
      consumes:
      - application/json
      description: Generate a radar chart
      parameters:
      - description: Request body to generate a radar chart
        in: body
        name: chart
        required: true
        schema:
          $ref: '#/definitions/requests.CreateChartRadar'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.File'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.APIError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/models.APIError'
      security:
      - Bearer: []
      summary: Generate a radar chart
      tags:
      - charts
  /files/base64/create:
    post:
      consumes:
      - application/json
      description: Add base64 file. Send file_path to save with custom name. Send
        width and height to resize.
      parameters:
      - description: Add image
        in: body
        name: file
        required: true
        schema:
          $ref: '#/definitions/requests.CreateBase64FileInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.File'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.APIError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/models.APIError'
      security:
      - Bearer: []
      summary: Add base64 file
      tags:
      - files
  /forgot_password:
    post:
      consumes:
      - application/json
      description: Forgot password by json user
      parameters:
      - description: Forgot password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.ForgotPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.APIError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Forgot password
      tags:
      - users
  /images/base64/create:
    post:
      consumes:
      - application/json
      description: Add base64 image. Send file_path to save with custom name. Send
        width and height to resize.
      parameters:
      - description: Add image
        in: body
        name: image
        required: true
        schema:
          $ref: '#/definitions/requests.CreateBase64ImageInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Image'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.APIError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/models.APIError'
      security:
      - Bearer: []
      summary: Add base64 image
      tags:
      - images
  /login:
    post:
      consumes:
      - application/json
      description: Login by json user
      parameters:
      - description: Add user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.APIError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Login an user
      tags:
      - users
  /recover_password:
    post:
      consumes:
      - application/json
      description: Recover password by json user
      parameters:
      - description: Recover password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.RecoverPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.APIError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Recover password
      tags:
      - users
  /status:
    get:
      consumes:
      - application/json
      description: Get api status
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.APIStatus'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.APIError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/models.APIError'
      summary: Get api status
      tags:
      - status
  /users:
    get:
      consumes:
      - application/json
      description: Get users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.APIError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/models.APIError'
      security:
      - Bearer: []
      summary: Get users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: add by json user
      parameters:
      - description: Add user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.CreateUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.APIError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/models.APIError'
      security:
      - Bearer: []
      summary: Add an user
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete by user ID
      parameters:
      - description: ID
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.APIError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/models.APIError'
      security:
      - Bearer: []
      summary: Delete an user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Get user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.APIError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/models.APIError'
      security:
      - Bearer: []
      summary: Get user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update by json user
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.UpdateUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.APIError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/models.APIError'
      security:
      - Bearer: []
      summary: Update an user
      tags:
      - users
  /users/{id}/update_fcm_token:
    put:
      consumes:
      - application/json
      description: Update by json user
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update user fcm token
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.UpdateUserFcmTokenInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.APIError'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/models.APIError'
      security:
      - Bearer: []
      summary: Update an user fcm token
      tags:
      - users
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
